Backporting tons of awesomeness from EU and PowerWellness into the Skeleton's bin directory.
This really needs to be broken out as a submodule at this point as most of the scripts are well tested and ready for use in other projects.

diff --git a/bin/init-repo b/bin/init-repo
--- a/bin/init-repo
+++ b/bin/init-repo
@@ -1,56 +1,151 @@
 #!/usr/bin/env bash
-# @TODO: Description.
+# Initializes a freshly cloned copy of the project for local usage.
 
-DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )";
-#TODO: Add smarts to (roughly) detect cake version and handle differences like "Config/" vs. "config/" intelligently so the script doesn't need to be customized for every project.
-CONFIG_DIR="$DIR/Config";
-CAKE="$( ls Lib )";
+#---------------------------------------------------------------------
+usage ()
+{
+	cat <<EOT
 
-#TODO: These vars should probably be prompts.
-DEFAULT_DEV_DATABASE=$1
-DEFAULT_TEST_DATABASE="${1}_test"
+${0##*/}  
+    Sets a freshly-cloned copy of a project for local use. The script 
+    is designed to be portable, without modification, between projects 
+    that may or may not implement various features (like migrations or 
+    the seedshell) and call those components only if they are found to 
+    be available. It does however depend on a variety of subscripts 
+    that should accompany it in the bin/ folder. Should be run from
+    the project root folder.
 
-# Initialize submodules
-git submodule update --init --recursive
+Usage:
+    ${0##*/} [env] [owner] [group] [db base name] [cake core path]
+    
+	- Checks for an existing ./Lib/Cake folder or symlink, and if 
+	  necessary prompts you for a full path to the correct core and 
+	  creates the link.
+	- Collects the correct environment (prod/dev/staging/etc) in use 
+	  either from the command line or user prompt, and copies the 
+	  correct default configs into place.
+	- Collects the correct user:group either from the command line or 
+	  user prompt to use for filesystem permissions.
+	- Initializes git submodules.
+	- Asks for DB credentials and writes them into Config/database.php 
+	  for you.
+	- Reads Config/writedirs.txt and makes those directories universally 
+	  writeable.
+	- Runs all database migrations, if the plugin is present and 
+	  Config/Migrations is not empty.
+	- If a SeedShell is available, asks if you want to populate sample 
+	  data.
 
-#TODO: This if statement could prompt for the path to the correct Cake folder if it doesn't exist, and create the symlink itself before proceeding.
-if [ ! -z "$CAKE" ]; then
-	
-	#TODO: Should add some sanity checks to stop the script from running on an existing (already configured) setup. Maybe check for config/core.php and config/database.php before proceeding?
-	
-	# Setup core.php and database.php
-	cp $CONFIG_DIR/core.php.default $CONFIG_DIR/core.php
-	cp $CONFIG_DIR/database.php.default $CONFIG_DIR/database.php
-	echo "Enter the development database name [${DEFAULT_DEV_DATABASE}]:"
-	read DEV_DATABASE
-	echo "Enter the development database name [${DEFAULT_TEST_DATABASE}]:"
-	read TEST_DATABASE
-	if [ ! $DEV_DATABASE ]; then
-		DEV_DATABASE=$DEFAULT_DEV_DATABASE
-	fi
-	if [ ! $TEST_DATABASE ]; then
-		TEST_DATABASE=$DEFAULT_TEST_DATABASE
-	fi
-	awk -v var=$DEV_DATABASE '{ gsub(/dev_database/,var,$0); print }' $CONFIG_DIR/database.php > $CONFIG_DIR/database.php.tmp
-	mv $CONFIG_DIR/database.php.tmp $CONFIG_DIR/database.php
-	awk -v var=$TEST_DATABASE '{ gsub(/test_database/,var,$0); print }' $CONFIG_DIR/database.php > $CONFIG_DIR/database.php.tmp
-	mv $CONFIG_DIR/database.php.tmp $CONFIG_DIR/database.php
 
-	# Make tmp directories writable
-	$DIR/bin/writedirs
+EOT
 
-	# Run migrations
-	$DIR/Console/cake Migrations.migration run all -p Migrations
-	$DIR/Console/cake Migrations.migration run all -p Queue
-	$DIR/bin/migrations
+	exit 0
+}
+if [ "$1" = '-h' ]; then
+	usage
+fi
 
-	# Seed database with data and optionally test data
+
+# Variable initialization.
+DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"
+BIN_DIR="$DIR/bin"
+CONFIG_DIR="$DIR/Config"
+CAKE_DIR="$DIR/Lib/Cake"
+DEFAULT_DBUSER="root"
+DEFAULT_DBPASS=""
+DEFAULT_SEEDSHELL="$DIR/Console/Command/SeedShell.php"
+
+# Input processing.
+if [ -n "$5" ]; then
+	# This path is ignored if the Lib/Cake symlink is already present.
+	ARG_CAKECOREDIR=$5
+elif [ ! -e "$CAKE_DIR" ]; then
+	# If the symlink doesn't already exist (and it wasn't passed as an argument), prompt the user for the full path to the core to use.
+	echo 'Enter the full path to the Cake .../lib/Cake folder you wish to use: '
+	read ARG_CAKECOREDIR
+fi
+# Take a detour and make sure the project has a Cake core available now if necessary so as not to force the user to enter a bunch of other information just to have the script fail anyway.
+$BIN_DIR/symlink-cake-core $ARG_CAKECOREDIR
+if [ $? -gt 0 ]; then
+	echo "!! Failed to link to Cake core. Aborting." >&2
+	exit 1
+fi
+
+if [ -n "$4" ]; then
+	ARG_DBNAME=$4
+else
+	echo 'Enter your local database name: '
+	read ARG_DBNAME
+fi
+
+# Take another slight detour for the sake of the user's sanity and gather "every time" necessary input about the DB.
+echo "Enter the database user name [${DEFAULT_DBUSER}]: "
+read ARG_DBUSER
+if [ -z "$ARG_DBUSER" ]; then
+	ARG_DBUSER=$DEFAULT_DBUSER
+fi
+
+echo "Enter the database user password [${DEFAULT_DBPASS}]: "
+read ARG_DBPASS
+if [ -z "$ARG_DBPASS" ]; then
+	ARG_DBPASS=$DEFAULT_DBPASS
+fi
+
+# Back to command line argument processing.
+if [ -n "$3" ]; then
+	ARG_GROUP=$3
+else
+	ARG_GROUP="$( ls -l ${DIR}/.. | grep $( basename $( pwd ) ) | awk '{ print $4 }' )"
+fi
+
+if [ -n "$2" ]; then
+	ARG_OWNER=$2
+else
+	# Default to the owner of the project's root directory. 
+	ARG_OWNER="$( ls -l ${DIR}/.. | grep $( basename $( pwd ) ) | awk '{ print $3 }' )"
+fi
+
+if [ -n "$1" ]; then
+	ARG_ENV=$1
+else
+	# Default, simply, to dev, which is safer than prod.
+	ARG_ENV="dev"
+	# Or require at least the environment argument and die here, spitting out usage and exiting.
+	#usage
+fi
+
+
+
+
+# Copy the correct config files into place.
+$BIN_DIR/set-configs $ARG_ENV
+
+# Update the database config with the proper credentials.
+$BIN_DIR/db-writeconfig $ARG_DBNAME $ARG_DBUSER "$ARG_DBPASS"
+
+# Load submodules.
+$BIN_DIR/git-submodules
+
+# Set file ownership.
+$BIN_DIR/set-owner $ARG_OWNER $ARG_GROUP
+
+# Give webserver permissions on specified files/folders.
+$BIN_DIR/writedirs
+
+# Check for Migrations (or Schema (or schema.sql)) and if present, run.
+$BIN_DIR/db-loadschema
+
+# Check for a SeedShell and if present, prompt to run it.
+if [ -e "$DEFAULT_SEEDSHELL" ]; then
+	echo "## Found a SeedShell for populating sample data in the database."
 	$DIR/Console/cake seed fill
-	echo 'Would you like to seed the database with test data [y/n]:'
-	read SEED
-	if [ $SEED == 'y' ]; then
+	echo 'Would you like to seed the database with sample data? [y/n]:'
+	read ANSWER
+	if [ $ANSWER == 'y' ]; then
 		$DIR/Console/cake seed fill test
 	fi
 else
-	echo 'CakePHP core needs to be copied or linked into Lib'
+	echo "## No SeedShell is present. You will have to populate sample data in the database yourself."
 fi
+
+echo "## Project initialization complete."
diff --git a/bin/update b/bin/update
--- a/bin/update
+++ b/bin/update
@@ -1,18 +1,164 @@
 #!/usr/bin/env bash
 
-DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )";
+#---------------------------------------------------------------------
+usage ()
+{
+	cat <<EOT
 
-git fetch --all --tags --prune
+${0##*/}  
+    Designed to perform all the necessary steps to update a local 
+    copy of the project from the remote repo, which is assumed to 
+    be "ahead" of the local copy. Mainly intended for use in 
+    staging and production environments to ensure that code "pushes" 
+    are performed consistently every time. Should be run from the 
+    project root folder.
 
-# Update repository
-if [ $1 ]; then
-	git checkout $1
-else
-	git pull
+Usage:
+    bin/${0##*/} [tag|branch|sha|ref] [dev|prod|staging] [user] [group]
+
+	$1 = The new commit to update to. Default: 'origin/master'
+	$2 = The local config file "environment" to use. Default: 'prod'
+	$3 = The local user to associate the project with. Default: owner of ./
+	$4 = The local group to associate the project with. Default: group of ./
+
+
+EOT
+
+	exit 0
+}
+if [ "$1" = '-h' ]; then
+	usage
 fi
 
-git submodule update --init --recursive
 
-$DIR/bin/migrations
-$DIR/bin/clear-cache
-$DIR/bin/writedirs
+echo "## Starting update process."
+
+# Set variables.
+DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )"
+BIN_DIR="$DIR/bin"
+CONFIG_DIR="$DIR/Config"
+MIGRATION_DIR="$CONFIG_DIR/Migration"
+SLEEP_TIME=10
+DEFAULT_DBUPDATES_FILE="$CONFIG_DIR/sql/db_updates.sql"
+
+
+# Input processing.
+if [ $1 ]; then
+	ARG_NEWCOMMIT=$1
+else
+	ARG_NEWCOMMIT="origin/master"
+fi
+
+if [ $2 ]; then
+	ARG_APPENV="$2"
+else
+	ARG_APPENV="prod"
+fi
+
+if [ $3 ]; then
+	ARG_OWNER=$3
+else
+	ARG_OWNER=""
+fi
+
+if [ $4 ]; then
+	ARG_GROUP=$4
+else
+	ARG_GROUP=""
+fi
+
+
+# Check for local changes that would cause a merge (without -f) will fail later.
+$BIN_DIR/git-localchanges
+if [ $? -gt 0 ]; then
+	echo "!! You will need to resolve any differences between the working copy  !!"
+	echo "!! and the active commit before proceeding with the update.           !!"
+	echo ""
+	exit 1
+fi
+
+
+# Backup the live DB.
+$BIN_DIR/db-backup
+echo ''
+echo "## Sleeping for ${SLEEP_TIME} seconds to give you time to think about if the "
+echo "##   backup size list above is appropriate. (Press Ctrl-C to abort the update)..."
+echo ''
+sleep ${SLEEP_TIME}
+
+
+# Save the "current" commit for later.
+EXISTINGCOMMIT=$( git rev-parse HEAD )
+EXISTINGBRANCH=$( git rev-parse --abbrev-ref HEAD )
+echo "## Current commit is $EXISTINGBRANCH ($EXISTINGCOMMIT)";
+
+
+# Update repository.
+echo "## Pulling changes from remote repo.";
+git fetch --tags
+git fetch origin
+
+
+# Apply database updates, one way or another.
+if [ -d "$MIGRATION_DIR" ] && [ "$(ls -A $MIGRATION_DIR)" ]; then
+	echo "## Running database migrations."
+	$BIN_DIR/migrations
+elif [ -e "$DEFAULT_DBUPDATES_FILE" ]; then
+	# Show manual pending DB updates to user. (Or use possibly use bin/db-apply-updates here to execute the SQL against the DB automatically, 
+	# which should be fairly recoverable if it's wrong [which it can be] considering we have already made a backup.)
+	DB_CHANGES="$( $BIN_DIR/db-show-updates $EXISTINGCOMMIT $ARG_NEWCOMMIT)"
+	if [ -n "$DB_CHANGES" ]; then
+		echo "## There are database updates to apply!"
+		echo '---------'
+		echo ''
+		echo "$DB_CHANGES"
+		echo ''
+		echo '---------'
+		echo ''
+		read -p "Press [ENTER] to continue when these updates have been applied to the local DB."
+	else
+		echo "## No database updates to apply.";
+	fi
+else
+	echo "## Could not automatically determine database change tracking system."
+	read -p "## Make sure any pending DB changes have been made and press [ENTER] to continue."
+fi
+
+
+
+# This if case should really be looking to see if we're being asked to fast forward on the same branch, or switch to the HEAD of a different branch.
+# if [ "$ARG_NEWCOMMIT" = "origin/master" ]; then
+	echo "## Merging upstream changes from: $ARG_NEWCOMMIT";
+	git merge $ARG_NEWCOMMIT
+# else
+# 	echo "## Checking out new commit: $ARG_NEWCOMMIT";
+# 	git checkout $ARG_NEWCOMMIT
+# fi
+
+
+echo "## New commit is now active:";
+git log -1
+
+
+# Copy the correct config files into place for this environment.
+$BIN_DIR/set-configs $ARG_APPENV
+
+
+# Load submodules.
+$BIN_DIR/git-submodules
+
+
+# Purge cache folders.
+$BIN_DIR/clear-cache
+
+
+# Set file ownership.
+$BIN_DIR/set-owner ${ARG_OWNER} ${ARG_GROUP}
+
+
+# Set write permissions.
+$BIN_DIR/writedirs
+
+
+echo "## Update process complete.";
+
