Updated spawn to be composer-friendly.

diff --git a/skelbin/spawn b/skelbin/spawn
--- a/skelbin/spawn
+++ b/skelbin/spawn
@@ -9,16 +9,15 @@ ${0##*/}
     Automates the process of spawning new projects from the 
     CakePHP-Skeleton project.
 
-    Before running this, you should have two local databases set up for 
-    the development and test versions of the project. Look at README.md 
-    for details.
+    Before running this, you should run `composer install` to make a Cake core
+    available and have two local databases set up for the development and test
+    versions of the new project. Look at README.md for details.
 
 Usage:
-    ${0##*/} <cake core path> <new app path> <git remote URL>
+    ${0##*/} <new app path> <git remote URL>
 
-	$1 = Absolute path to lib/Cake. Must be Cake v2.3.0 or higher.
-	$2 = Path to the folder you want to create the new project in.
-	$3 = Remote git repo URL to add as the 'origin' for the new project.
+	$1 = Path to the folder you want to create the new project in.
+	$2 = Remote git repo URL to add as the 'origin' for the new project.
 
 
 EOT
@@ -34,39 +33,38 @@ fi
 DIR="$( cd -P "$( dirname "$0" )"/.. && pwd )";
 DIR_TMP="${DIR}/tmp"
 DIR_SKELETON_SEED="cakeskel"
+DIR_CAKE_REL="Vendor/pear-pear.cakephp.org/CakePHP/Cake"
+DIR_CAKE_CORE="${DIR}/${DIR_CAKE_REL}"
 
 # Input checking.
-if [ -z "$1" ]; then
-	echo "!! No Cake core path provided."  >&2
-	usage
-	exit 1
+if [ ! -d "$DIR_CAKE_CORE" ]; then
+	echo "!! Cake core not found in expected path: ${DIR_CAKE_CORE}"  >&2
+	echo "   Trying to run `composer install` for you..."
+	composer install
+	if [ !-d "$DIR_CAKE_CORE" ]; then
+		echo "!! Couldn't run `composer install`. Aborting."  >&2
+		usage
+		exit 1
+	fi
 fi
 
-if [ -d "$1" ]; then
-	echo "## Setting Cake core path to: ${1}" >&2
-	DIR_CAKE_CORE=$1
-else
-	echo "!! Bad Cake core path provided."  >&2
-	usage
-	exit 1
-fi
-
-if [ -n "$2" ]; then
-	echo "## Setting new app path to: ${2}" >&2
-	DIR_NEW_APP=$2
+if [ -n "$1" ]; then
+	echo "## Setting new app path to: ${1}" >&2
+	DIR_NEW_APP=$1
 else
 	echo "!! No path provided for new app."  >&2
 	usage
 	exit 1
 fi
 
-if [ -n "$3" ]; then
-	echo "## Setting git repo URL to: ${3}" >&2
-	URL_REPO=$3
+if [ -n "$2" ]; then
+	echo "## Setting git repo URL to: ${2}" >&2
+	URL_REPO=$2
 else
 	echo "!! No remote git repo URL provided."  >&2
-	usage
-	exit 1
+	URL_REPO=0
+	#usage
+	#exit 1
 fi
 
 
@@ -81,54 +79,62 @@ if [ -d "${DIR_TMP}/${DIR_SKELETON_SEED}" ]; then
 fi
 
 
-echo "## Creating skeleton seed copy at: ${DIR_TMP}/${DIR_SKELETON_SEED}" >&2
+echo "## Creating skeleton seed copy from git HEAD at: ${DIR_TMP}/${DIR_SKELETON_SEED}" >&2
 cd $DIR
-git archive HEAD --format=zip > ${DIR_TMP}/archive.zip
+git archive HEAD --format=zip --output=${DIR_TMP}/archive.zip
 cd ${DIR_TMP}
 unzip -qd ${DIR_SKELETON_SEED} archive.zip
 
 
 echo "## Tweaking the skeleton seed copy before baking." >&2
 rm -rf ${DIR_TMP}/${DIR_SKELETON_SEED}/skelbin
-cp ${DIR_TMP}/${DIR_SKELETON_SEED}/Config/core.php.default ${DIR_TMP}/${DIR_SKELETON_SEED}/Config/core.php
-
+mv -f ${DIR_TMP}/${DIR_SKELETON_SEED}/composer-skel.json ${DIR_TMP}/${DIR_SKELETON_SEED}/composer.json
 
 echo "## Creating destination folder: ${DIR_NEW_APP}" >&2
-mkdir -p ${DIR_NEW_APP}/Lib
+mkdir -p ${DIR_NEW_APP}
 
 
-echo "## Linking Cake core at: ${DIR_NEW_APP}/Lib/Cake" >&2
-ln -s ${DIR_CAKE_CORE}/lib/Cake ${DIR_NEW_APP}/Lib/Cake
-#ln -s ${DIR_CAKE_CORE}/lib/Cake ${DIR_NEW_APP}/lib/Cake
-
-
-echo "## Baking new project. (Ignore any warnings about CAKE_CORE_INCLUDE_PATH.)" >&2
+echo "## Baking new project." >&2
+echo "   (Ignore any warnings about cache prefix, app/Console and CAKE_CORE_INCLUDE_PATH.)" >&2
 cd `dirname ${DIR_NEW_APP}`
-${DIR_NEW_APP}/Lib/Cake/Console/cake bake project --skel ${DIR_TMP}/${DIR_SKELETON_SEED} ${DIR_NEW_APP}
+${DIR}/bin/cake bake project --skel ${DIR_TMP}/${DIR_SKELETON_SEED} ${DIR_NEW_APP}
 
+
+
+echo "## Cleaning up new README." >&2
 cd ${DIR_NEW_APP}
-cp ${DIR_NEW_APP}/Config/core.php ${DIR_NEW_APP}/Config/core.php.default
+
 sed -e '1,/---/d;/---/,$p' -i '' "${DIR_NEW_APP}/README.md"
+
 
 #@TODO: Also run the project's README.md through a pass with m4, adding in the repo URL, project name, and anything else we already know about it from this script run.
 
+#@TODO: Really we need to run a wizard here to ask for the proper values for a bunch of the config files (composer.json[name, description], Config/env_vars.txt, Lib/puphpet/config.yaml, etc.)
 
 echo "## Setting up git repo for new project." >&2
 git init
-git remote add origin ${URL_REPO}
+if [ ${URL_REPO} -ne 0 ]; then
+	git remote add origin ${URL_REPO}
+else
+	echo "## Skipped adding remote (none provided)." >&2
+fi
 
-#@TODO: Init project's submodules, in order to pull in the bin/ folder.
+echo "## Priming dependencies for new project." >&2
+composer install
+bin/git-submodules
 
-#@TODO: In the newly spawned project, update the bin/ submodule version to the latest master release. (bin/bin-selfupdate)
 
-#@TODO: Offer to write database.php settings for you. If [y], prompt for each input (host, dbname, user, pass, prefix)  then run bin/db-writeconfig. Remove #1 in list below when this is automated.
+echo "## Adding local/vagrant DB configs." >&2
+bin/db-writeconfigs DB_NAME user '' localhost
 
 #@TODO: Offer to run schema generate -f. Remove #2 below when this is complete.
 
 echo "## Done. You should:" >&2
-echo "##    - Set up Config/database.php." >&2
-echo "##    - Run \`Console/cake schema generate -f\`." >&2
+echo "##    - Run \`Console/cake schema generate -f\` (from inside vagrant)." >&2
 echo "##    - Add project information to the README.md file." >&2
 echo "##    - Commit and push everything to the remote repo." >&2
+
+
+exit 0
 
 
